language: php
sudo: false

matrix:
    include:
        - os: linux
          dist: trusty
          php: hhvm
        - os: linux
          dist: precise
          php: 5.4
        - os: linux
          dist: precise
          php: 5.5
        - os: linux
          dist: precise
          php: 5.6
        - os: linux
          dist: trusty
          php: 7
        - os: linux
          dist: trusty
          php: 7.1
        - os: linux
          dist: trusty
          php: nightly

before_script:
  - composer self-update
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
