dist: trusty
sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - nightly

before_script:
  - composer self-update
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

jobs:
  include:
    - stage: travis
      dist: precise
      script:
        - composer self-update
        - composer install
        - ./vendor/bin/phpunit
      php: hhvm
