language: php
sudo: false

matrix:
    include:
        - os: linux
          dist: trusty
          php: 
            - hhvm
            - 7
            - 7.1
            - nightly
        - os: linux
          dist: precise
          php: 
            - 5.4
            - 5.5
            - 5.6        

before_script:
  - composer self-update
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
