<?php
namespace aura\view\helper;

/**
 * Test class for AnchorRaw.
 * Generated by PHPUnit on 2011-04-02 at 08:28:20.
 */
class AnchorRawTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @todo Implement test__invoke().
     */
    public function test__invoke()
    {
        $href = '/path/to/script.php?foo=bar&zim=gir';
        $anchor_raw = new AnchorRaw;
        $actual = $anchor_raw($href, '<this>');
        $expect = '<a href="/path/to/script.php?foo=bar&amp;zim=gir"><this></a>';
        $this->assertSame($expect, $actual);
    }
}
