<?php
namespace aura\view\helper;

/**
 * Test class for Links.
 * Generated by PHPUnit on 2011-04-02 at 08:28:49.
 */
class LinksTest extends \PHPUnit_Framework_TestCase
{
    public function test__invoke()
    {
        $links = new Links;
        $this->assertType('aura\view\helper\Links', $links);
        
        $links->add(array(
            'rel' => 'prev',
            'href' => '/path/to/prev?this&that',
        ));
        
        $links->add(array(
            'rel' => 'next',
            'href' => '/path/to/next?this&that',
        ));
        
        $actual = $links->get();
        $expect = '    <link rel="prev" href="/path/to/prev?this&amp;that" />' . PHP_EOL
                . '    <link rel="next" href="/path/to/next?this&amp;that" />' . PHP_EOL;
       
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetIndent().
     */
    public function testSetIndent()
    {
        $links = new Links;
        $this->assertType('aura\view\helper\Links', $links);
        
        $links->setIndent('  ');
        
        $links->add(array(
            'rel' => 'prev',
            'href' => '/path/to/prev?this&that',
        ));
        
        $links->add(array(
            'rel' => 'next',
            'href' => '/path/to/next?this&that',
        ));
        
        $actual = $links->get();
        $expect = '  <link rel="prev" href="/path/to/prev?this&amp;that" />' . PHP_EOL
                . '  <link rel="next" href="/path/to/next?this&amp;that" />' . PHP_EOL;
       
        $this->assertSame($expect, $actual);
    }
}
