<?php
namespace Aura\View\helper;

/**
 * Test class for Title.
 * Generated by PHPUnit on 2011-04-02 at 08:29:14.
 */
class TitleTest extends \PHPUnit_Framework_TestCase
{
    public function test__invoke()
    {
        $title = new Title;
        $actual = $title();
        $this->assertType('Aura\View\helper\Title', $actual);
    }
    
    /**
     * @todo Implement test__invoke().
     */
    public function testEverything()
    {
        $title = new Title;
        
        $this->assertType('Aura\View\helper\Title', $title);
        
        $title->set('This & That');
        
        $title->append(' Suf1');
        $title->append(' Suf2');
        
        $title->prepend('Pre1 ');
        $title->prepend('Pre2 ');
        
        $actual = $title->get();
        $expect = '    <title>Pre2 Pre1 This &amp; That Suf1 Suf2</title>' . PHP_EOL;
        $this->assertSame($expect, $actual);
        
        $actual = $title->getRaw();
        $expect = '    <title>Pre2 Pre1 This & That Suf1 Suf2</title>' . PHP_EOL;
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetIndent().
     */
    public function testSetIndent()
    {
        $title = new Title;
        $title->setIndent('  ');
        $title->set('This & That');
        $actual = $title->get();
        $expect = '  <title>This &amp; That</title>' . PHP_EOL;
        $this->assertSame($expect, $actual);
    }
}
