<?php
namespace aura\view;

use aura\di\Forge;
use aura\di\Config;

/**
 * Test class for HelperRegistry.
 * Generated by PHPUnit on 2011-03-27 at 14:44:05.
 */
class HelperRegistryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HelperRegistry
     */
    protected $registry;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $forge = new Forge(new Config);
        $this->registry = new HelperRegistry($forge);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @todo Implement testGet().
     */
    public function testGetInstance()
    {
        // can we get a helper?
        $first = $this->registry->getInstance('aura\view\helper\Escape');
        $this->assertType('aura\view\helper\Escape', $first);
        
        // is it always the same?
        $again = $this->registry->getInstance('aura\view\helper\Escape');
        $this->assertSame($first, $again);
    }
}
