<?php
namespace aura\view;

/**
 * Test class for Plugin.
 * Generated by PHPUnit on 2011-03-27 at 14:44:02.
 */
class PluginTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Plugin
     */
    protected $plugin;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->plugin = new MockPlugin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @todo Implement testSetEscapeQuotes().
     */
    public function testSetEscapeQuotes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetEscapeCharset().
     */
    public function testSetEscapeCharset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
    
    public function test__invoke()
    {
        $plugin = $this->plugin;
        $actual = $plugin();
        $expect = "Hello Plugin";
        $this->assertSame($expect, $actual);
    }
}
