<?php
namespace aura\view;

/**
 * Test class for PluginRegistry.
 * Generated by PHPUnit on 2011-03-27 at 14:44:05.
 */
class PluginRegistryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PluginRegistry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new PluginRegistry;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @todo Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
