<?php
namespace aura\view;
use aura\di\Forge;
use aura\di\Config;

/**
 * Test class for Template.
 * Generated by PHPUnit on 2011-03-27 at 14:44:16.
 */
class TemplateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Template
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }
    
    protected function newTemplate(array $paths = array())
    {
        $forge = new Forge(new Config);
        $finder = new Finder($paths);
        $map = array('mockPlugin' => 'aura\view\MockPlugin');
        $plugin_registry = new PluginRegistry($forge, $map);
        return new Template($finder, $plugin_registry);
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @todo Implement test__get().
     */
    public function test__setGetIssetUnset()
    {
        $template = $this->newTemplate();
        $this->assertFalse(isset($template->foo));
        $template->foo = 'bar';
        $this->assertTrue(isset($template->foo));
        $this->assertSame('bar', $template->foo);
        unset($template->foo);
        $this->assertFalse(isset($template->foo));
    }
    
    /**
     * @todo Implement test__call().
     */
    public function test__call()
    {
        $template = $this->newTemplate();
        $expect = 'Hello Plugin';
        $actual = $template->mockPlugin();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetData().
     */
    public function testSetAndGetData()
    {
        $template = $this->newTemplate();
        $expect = array();
        $actual = $template->getData();
        $this->assertSame($expect, $actual);
        
        $data = array(
            'foo' => 'bar'
        );
        
        $template->setData($data);
        $this->assertSame('bar', $template->foo);
        
        $actual = $template->getData();
        $this->assertSame($data, $actual);
    }

    public function testEscape()
    {
        $template = $this->newTemplate();
        
        $raw = '<\'single\' "double">';
        $expect = '&lt;&#039;single&#039; &quot;double&quot;&gt;';
        $actual = $template->escape($raw);
        $this->assertSame($expect, $actual);
        
        $template->setEscapeQuotes(ENT_COMPAT);
        $raw = '<\'single\' "double">';
        $expect = '&lt;\'single\' &quot;double&quot;&gt;';
        $actual = $template->escape($raw);
        $this->assertSame($expect, $actual);
        
        // should add some alternative chars here (like euro sign)
        $template->setEscapeCharset('ISO-8859-15');
        $raw = '<\'single\' "double">';
        $expect = '&lt;\'single\' &quot;double&quot;&gt;';
        $actual = $template->escape($raw);
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testFind().
     */
    public function testFind()
    {
        // prepare a set of directories and files
        $base = __DIR__ . DIRECTORY_SEPARATOR . 'tmp';
        $list = array('foo', 'bar', 'baz');
        $dirs = array();
        foreach ($list as $dir) {
            // make dir for the finder
            $dirs[$dir] = $base . DIRECTORY_SEPARATOR . $dir;
            mkdir($dirs[$dir], 0777, true);
            
            // place the same file in each dir
            $file = $dirs[$dir] . DIRECTORY_SEPARATOR . 'zim.php';
            file_put_contents($file, 'empty');
        }
        
        // now find it; should be the same as the one at the beginning
        // of the paths
        $template = $this->newTemplate($dirs);
        $actual = $template->find('zim');
        $expect = $dirs['foo'] . DIRECTORY_SEPARATOR . 'zim.php';
        $this->assertSame($expect, $actual);
        
        // remove the directories and files
        foreach ($dirs as $dir) {
            unlink($dir . DIRECTORY_SEPARATOR . 'zim.php');
            rmdir($dir);
        }
    }
    
    public function testFetch()
    {
        // the template file
        $file = __DIR__ . DIRECTORY_SEPARATOR
              . 'tmp' . DIRECTORY_SEPARATOR
              . 'fetch' . DIRECTORY_SEPARATOR
              . 'zim.php';
        
        // the template code
        $code = '<?php echo $this->mockPlugin() . " " . $this->foo;';
        
        // put it in place
        $dir = dirname($file);
        mkdir($dir, 0777, true);
        file_put_contents($file, $code);
        
        // get a template object
        $template = $this->newTemplate(array($dir));
        $template->foo = 'bar';
        $actual = $template->fetch('zim');
        $expect = 'Hello Plugin bar';
        $this->assertSame($expect, $actual);
        
        // remove the file and dir
        unlink($file);
        rmdir($dir);
    }
    
    public function testFetchExtract()
    {
        // the template file
        $file = __DIR__ . DIRECTORY_SEPARATOR
              . 'tmp' . DIRECTORY_SEPARATOR
              . 'fetch' . DIRECTORY_SEPARATOR
              . 'foo.php';
        
        // the template code
        $code = '<?php echo $this->mockPlugin() . " " . $foo;';
        
        // put it in place
        $dir = dirname($file);
        mkdir($dir, 0777, true);
        file_put_contents($file, $code);
        
        // get a template object
        $template = $this->newTemplate(array($dir));
        $actual = $template->fetch('foo', array('foo' => 'dib'));
        $expect = 'Hello Plugin dib';
        $this->assertSame($expect, $actual);
        
        // remove the file and dir
        unlink($file);
        rmdir($dir);
    }
    
    /**
     * @expectedException aura\view\Exception_TemplateNotFound
     */
    public function testFindTemplateNotFound()
    {
        $template = $this->newTemplate();
        $template->find('no_such_template');
    }
}
