<?php
namespace Aura\View\Helper;

/**
 * Test class for Base.
 * Generated by PHPUnit on 2011-04-02 at 08:28:30.
 */
class BaseTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $base = new Base;
        $base->setIndentLevel(1);
        $href = '/path/to/base';
        $actual = $base($href);
        $expect = '        <base href="/path/to/base" />' . PHP_EOL;
        $this->assertSame($expect, $actual);
    }
}
