<?php
namespace Aura\View\Helper;

/**
 * Test class for Styles.
 * Generated by PHPUnit on 2011-04-02 at 08:29:10.
 */
class StylesTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $styles = new Styles;
        $actual = $styles();
        $this->assertInstanceOf('Aura\View\Helper\Styles', $actual);
    }
    
    public function testAddAndGet()
    {
        $styles = new Styles;
        
        $styles->add('/css/middle.css');
        $styles->add('/css/last.css', null, 150);
        $styles->add('/css/first.css', null, 50);
        $styles->addCond('ie6', '/css/ie6.css');
        
        $actual = $styles->get();
        $expect = '    <link rel="stylesheet" href="/css/first.css" type="text/css" media="screen" />' . PHP_EOL
                . '    <link rel="stylesheet" href="/css/middle.css" type="text/css" media="screen" />' . PHP_EOL
                . '    <!--[if ie6]><link rel="stylesheet" href="/css/ie6.css" type="text/css" media="screen" /><![endif]-->' . PHP_EOL
                . '    <link rel="stylesheet" href="/css/last.css" type="text/css" media="screen" />' . PHP_EOL;
        
        $this->assertSame($expect, $actual);
    }
    
    /**
     * @todo Implement testSetIndent().
     */
    public function testSetIndentAndAttribs()
    {
        $styles = new Styles;
        
        $styles->setIndent('  ');
        $styles->add('/css/middle.css', ['media' => 'print']);
        $styles->add('/css/last.css', null, 150);
        $styles->add('/css/first.css', null, 50);
        $styles->addCond('ie6', '/css/ie6.css', ['media' => 'print']);
        $actual = $styles->get();
        
        $expect = '  <link rel="stylesheet" href="/css/first.css" type="text/css" media="screen" />' . PHP_EOL
                . '  <link rel="stylesheet" href="/css/middle.css" type="text/css" media="print" />' . PHP_EOL
                . '  <!--[if ie6]><link rel="stylesheet" href="/css/ie6.css" type="text/css" media="print" /><![endif]-->' . PHP_EOL
                . '  <link rel="stylesheet" href="/css/last.css" type="text/css" media="screen" />' . PHP_EOL;
        
        $this->assertSame($expect, $actual);
    }
}
