<?php
namespace Aura\View\Helper;

/**
 * Test class for Title.
 * Generated by PHPUnit on 2011-04-02 at 08:29:14.
 */
class TitleTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $title = new Title;
        $actual = $title();
        $this->assertInstanceOf('Aura\View\Helper\Title', $actual);
    }
    
    /**
     * @todo Implement test__invoke().
     */
    public function testEverything()
    {
        $title = new Title;
        $this->assertInstanceOf('Aura\View\Helper\Title', $title);
        
        $escaper = $this->escape((object) [
            'main' => 'This & That',
            'suf1' => ' Suf1',
            'suf2' => ' Suf2',
            'pre1' => 'Pre1 ',
            'pre2' => 'Pre2 ',
        ]);
        
        $title->set($escaper->main);
        
        $title->append($escaper->suf1);
        $title->append($escaper->suf2);
        
        $title->prepend($escaper->pre1);
        $title->prepend($escaper->pre2);
        
        $actual = $title->get();
        $expect = '    <title>Pre2 Pre1 This &amp; That Suf1 Suf2</title>' . PHP_EOL;
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetIndent().
     */
    public function testSetIndent()
    {
        $title = new Title;
        $title->setIndent('  ');
        $escaper = $this->escape((object) [
            'main' => 'This & That',
        ]);
        $title->set($escaper->main);
        $actual = $title->get();
        $expect = '  <title>This &amp; That</title>' . PHP_EOL;
        $this->assertSame($expect, $actual);
    }
}
