<?php
namespace Aura\View\Helper;

/**
 * Test class for Anchor.
 * Generated by PHPUnit on 2011-04-02 at 08:27:59.
 */
class AnchorTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $anchor = new Anchor;
        $actual = $anchor(
            $this->escape('/path/to/script.php?foo=bar&zim=gir'),
            $this->escape('<this>')
        );
        $expect = '<a href="/path/to/script.php?foo=bar&amp;zim=gir">&lt;this&gt;</a>';
        $this->assertSame($expect, $actual);
    }
    
    public function testWithAttr()
    {
        $anchor = new Anchor;
        
        $actual = $anchor(
            $this->escape('/path/to/script.php'),
            $this->escape('foo'),
            $this->escape(['bar' => 'baz', 'href' => 'skip-me'])
        );
        
        $expect = '<a href="/path/to/script.php" bar="baz">foo</a>';
        $this->assertSame($expect, $actual);
    }
}
