<?php
namespace Aura\View\Helper;

/**
 * Test class for Anchor.
 * Generated by PHPUnit on 2011-04-02 at 08:27:59.
 */
class AnchorTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $escaper = $this->escaper_factory->newInstance((object) [
            'href' => '/path/to/script.php?foo=bar&zim=gir',
            'text' => '<this>',
        ]);
        
        $anchor = new Anchor;
        $actual = $anchor($escaper->href, $escaper->text);
        $expect = '<a href="/path/to/script.php?foo=bar&amp;zim=gir">&lt;this&gt;</a>';
        $this->assertSame($expect, $actual);
    }
    
    public function testWithAttribs()
    {
        $escaper = $this->escaper_factory->newInstance((object) [
            'href' => '/path/to/script.php',
            'text' => 'foo',
            'attribs' => ['bar' => 'baz'],
        ]);
        
        $anchor = new Anchor;
        $actual = $anchor($escaper->href, $escaper->text, $escaper->attribs);
        $expect = '<a href="/path/to/script.php" bar="baz">foo</a>';
        $this->assertSame($expect, $actual);
    }
}
