<?php
namespace Aura\View\Helper;

/**
 * Test class for Anchor.
 * Generated by PHPUnit on 2011-04-02 at 08:27:59.
 */
class AnchorTest extends \PHPUnit_Framework_TestCase
{
    public function test__invoke()
    {
        $href = '/path/to/script.php?foo=bar&zim=gir';
        $anchor = new Anchor;
        $actual = $anchor($href, '<this>');
        $expect = '<a href="/path/to/script.php?foo=bar&amp;zim=gir">&lt;this&gt;</a>';
        $this->assertSame($expect, $actual);
    }
    
    public function testRaw()
    {
        $href = '/path/to/script.php?foo=bar&zim=gir';
        $anchor = new Anchor;
        $actual = $anchor->raw($href, '<this>');
        $expect = '<a href="/path/to/script.php?foo=bar&amp;zim=gir"><this></a>';
        $this->assertSame($expect, $actual);
    }
    
    public function testWithAttribs()
    {
        $href = '/path/to/script.php';
        $anchor = new Anchor;
        $actual = $anchor->raw($href, 'foo', ['bar' => 'baz']);
        $expect = '<a href="/path/to/script.php" bar="baz">foo</a>';
        $this->assertSame($expect, $actual);
    }
}
