<?php
namespace Aura\View\Helper;

/**
 * Test class for Base.
 * Generated by PHPUnit on 2011-04-02 at 08:28:30.
 */
class BaseTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $base = new Base;
        $actual = $base($this->escape('/path/to/base'));
        $expect = '<base href="/path/to/base" />' . PHP_EOL;
        $this->assertSame($expect, $actual);
    }
}
