<?php
namespace Aura\View\Helper;

/**
 * Test class for Datetime.
 * Generated by PHPUnit on 2011-04-02 at 08:28:35.
 */
class DatetimeTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $datetime = new Datetime(['special' => 'Ymd']);
        $spec = 'March 21, 2004, 11:45pm';
        
        // default format
        $expect = '2004-03-21 23:45:00';
        $actual = $datetime($this->escape($spec));
        $this->assertSame($expect, $actual);
        
        // preset format
        $expect = '23:45:00';
        $actual = $datetime($this->escape($spec), 'time');
        $this->assertSame($expect, $actual);
        
        // constructor-provided format
        $expect = '20040321';
        $actual = $datetime($this->escape($spec), 'special');
        $this->assertSame($expect, $actual);
        
        // custom format
        $actual = $datetime($this->escape($spec), 'd');
        $expect = '21';
        $this->assertSame($expect, $actual);
    }
}
