<?php
namespace Aura\View\Helper;

/**
 * Test class for Links.
 * Generated by PHPUnit on 2011-04-02 at 08:28:49.
 */
class LinksTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $links = new Links;
        $actual = $links();
        $this->assertInstanceOf('Aura\View\Helper\Links', $actual);
    }
    
    public function testAddAndGet()
    {
        $links = new Links;
        
        $prev = [
            'rel' => 'prev',
            'href' => '/path/to/prev?this&that',
        ];
        
        $next = [
            'rel' => 'next',
            'href' => '/path/to/next?this&that',
        ];
        
        $links->add($prev);
        $links->add($next);
        
        $actual = $links->get();
        $expect = '    <link rel="prev" href="/path/to/prev?this&that" />' . PHP_EOL
                . '    <link rel="next" href="/path/to/next?this&that" />' . PHP_EOL;
       
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetIndent().
     */
    public function testSetIndent()
    {
        $links = new Links;
        $links->setIndent('  ');
        
        $prev = [
            'rel' => 'prev',
            'href' => '/path/to/prev?this&that',
        ];
        
        $next = [
            'rel' => 'next',
            'href' => '/path/to/next?this&that',
        ];
        
        $links->add($prev);
        $links->add($next);
        
        $actual = $links->get();
        $expect = '  <link rel="prev" href="/path/to/prev?this&that" />' . PHP_EOL
                . '  <link rel="next" href="/path/to/next?this&that" />' . PHP_EOL;
       
        $this->assertSame($expect, $actual);
    }
}
