<?php
namespace Aura\View\Helper;

/**
 * Test class for Scripts.
 * Generated by PHPUnit on 2011-04-02 at 08:29:01.
 */
class ScriptsTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $scripts = new Scripts;
        $actual = $scripts();
        $this->assertInstanceOf('Aura\View\Helper\Scripts', $actual);
    }
    
    public function testSetIndent()
    {
        $scripts = new Scripts;
        $scripts->setIndent('  ');
        $scripts->setIndentLevel(1);
        
        $scripts->add($this->escape('/js/first.js'));
        $scripts->add($this->escape('/js/middle.js'));
        $scripts->add($this->escape('/js/last.js'));
        
        $actual = $scripts->get();
        
        $expect = '  <script src="/js/first.js" type="text/javascript"></script>' . PHP_EOL
                . '  <script src="/js/middle.js" type="text/javascript"></script>' . PHP_EOL
                . '  <script src="/js/last.js" type="text/javascript"></script>' . PHP_EOL;
        
        $this->assertSame($expect, $actual);
    }

    public function testAddAndGet()
    {
        $scripts = new Scripts;
        $scripts->add($this->escape('/js/last.js'), [], 150);
        $scripts->add($this->escape('/js/first.js'), [], 50);
        $scripts->add($this->escape('/js/middle.js'));
        $scripts->addCond($this->escape('ie6'), $this->escape('/js/ie6.js'));
        
        $actual = $scripts->get();
        
        $expect = '<script src="/js/first.js" type="text/javascript"></script>' . PHP_EOL
                . '<script src="/js/middle.js" type="text/javascript"></script>' . PHP_EOL
                . '<!--[if ie6]><script src="/js/ie6.js" type="text/javascript"></script><![endif]-->' . PHP_EOL
                . '<script src="/js/last.js" type="text/javascript"></script>' . PHP_EOL;
        
        $this->assertSame($expect, $actual);
    }
}
