<?php
namespace Aura\View\Helper;

/**
 * Test class for Scripts.
 * Generated by PHPUnit on 2011-04-02 at 08:29:01.
 */
class ScriptsTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $scripts = new Scripts;
        $actual = $scripts();
        $this->assertInstanceOf('Aura\View\Helper\Scripts', $actual);
    }
    
    /**
     * @todo Implement testSetIndent().
     */
    public function testSetIndent()
    {
        $scripts = new Scripts;
        $scripts->setIndent('  ');
        $scripts->add('/js/first.js');
        $scripts->add('/js/middle.js');
        $scripts->add('/js/last.js');
        
        $actual = $scripts->get();
        
        $expect = '  <script src="/js/first.js" type="text/javascript"></script>' . PHP_EOL
                . '  <script src="/js/middle.js" type="text/javascript"></script>' . PHP_EOL
                . '  <script src="/js/last.js" type="text/javascript"></script>' . PHP_EOL;
        
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testAddHead().
     */
    public function testAddAndGet()
    {
        $scripts = new Scripts;
        $scripts->add('/js/last.js', [], 150);
        $scripts->add('/js/first.js', [], 50);
        $scripts->add('/js/middle.js');
        $scripts->addCond('ie6', '/js/ie6.js');
        
        $actual = $scripts->get();
        
        $expect = '    <script src="/js/first.js" type="text/javascript"></script>' . PHP_EOL
                . '    <script src="/js/middle.js" type="text/javascript"></script>' . PHP_EOL
                . '    <!--[if ie6]><script src="/js/ie6.js" type="text/javascript"></script><![endif]-->' . PHP_EOL
                . '    <script src="/js/last.js" type="text/javascript"></script>' . PHP_EOL;
        
        $this->assertSame($expect, $actual);
    }
    
    /**
     * Tests add and get in a fluent interface
     */
    public function testAddAndGet_fluent()
    {
        $scripts = new Scripts;
        $actual = $scripts->add('/js/first.js')
                          ->add('/js/second.js')
                          ->add('/js/third.js')
                          ->addCond('IE6', '/js/ie6.js')
                          ->get();
                          
        $expect = '    <script src="/js/first.js" type="text/javascript"></script>' . PHP_EOL
                . '    <script src="/js/second.js" type="text/javascript"></script>' . PHP_EOL
                . '    <script src="/js/third.js" type="text/javascript"></script>' . PHP_EOL
                . '    <!--[if IE6]><script src="/js/ie6.js" type="text/javascript"></script><![endif]-->' . PHP_EOL;
        
        $this->assertSame($expect, $actual);
    }
}
