<?php
namespace Aura\View\Helper;

/**
 * Test class for Styles.
 * Generated by PHPUnit on 2011-04-02 at 08:29:10.
 */
class StylesTest extends AbstractHelperTest
{
    public function test__invoke()
    {
        $styles = new Styles;
        $actual = $styles();
        $this->assertInstanceOf('Aura\View\Helper\Styles', $actual);
    }
    
    public function testAddAndGet()
    {
        $styles = new Styles;
        
        $styles->add($this->escape('/css/middle.css'));
        $styles->add($this->escape('/css/last.css'), [], 150);
        $styles->add($this->escape('/css/first.css'), [], 50);
        $styles->addCond($this->escape('ie6'), $this->escape('/css/ie6.css'));
        
        $actual = $styles->get();
        $expect = '<link rel="stylesheet" href="/css/first.css" type="text/css" media="screen" />' . PHP_EOL
                . '<link rel="stylesheet" href="/css/middle.css" type="text/css" media="screen" />' . PHP_EOL
                . '<!--[if ie6]><link rel="stylesheet" href="/css/ie6.css" type="text/css" media="screen" /><![endif]-->' . PHP_EOL
                . '<link rel="stylesheet" href="/css/last.css" type="text/css" media="screen" />' . PHP_EOL;
        
        $this->assertSame($expect, $actual);
    }
    
    public function testSetIndentAndAttribs()
    {
        $styles = new Styles;
        
        $styles->setIndent('  ');
        $styles->setIndentLevel(1);
        
        $styles->add($this->escape('/css/middle.css'), $this->escape(['media' => 'print']));
        $styles->add($this->escape('/css/last.css'), [], 150);
        $styles->add($this->escape('/css/first.css'), [], 50);
        $styles->addCond($this->escape('ie6'), $this->escape('/css/ie6.css'), $this->escape(['media' => 'print']));
        $actual = $styles->get();
        
        $expect = '  <link rel="stylesheet" href="/css/first.css" type="text/css" media="screen" />' . PHP_EOL
                . '  <link rel="stylesheet" href="/css/middle.css" type="text/css" media="print" />' . PHP_EOL
                . '  <!--[if ie6]><link rel="stylesheet" href="/css/ie6.css" type="text/css" media="print" /><![endif]-->' . PHP_EOL
                . '  <link rel="stylesheet" href="/css/last.css" type="text/css" media="screen" />' . PHP_EOL;
        
        $this->assertSame($expect, $actual);
    }
}
