<?php
namespace Aura\Html\Helper;

/**
 * Test class for Title.
 * Generated by PHPUnit on 2011-04-02 at 08:29:14.
 */
class TitleTest extends \PHPUnit_Framework_TestCase
{
    public function test__invoke()
    {
        $title = new Title;
        $actual = $title();
        $this->assertInstanceOf('Aura\Html\Helper\Title', $actual);
    }
    
    /**
     * @todo Implement test__invoke().
     */
    public function testEverything()
    {
        $title = new Title;
        $this->assertInstanceOf('Aura\Html\Helper\Title', $title);
        
        $data = (object) [
            'main' => 'This and That',
            'suf1' => ' Suf1',
            'suf2' => ' Suf2',
            'pre1' => 'Pre1 ',
            'pre2' => 'Pre2 ',
        ];
        
        $title->set($data->main);
        
        $title->append($data->suf1);
        $title->append($data->suf2);
        
        $title->prepend($data->pre1);
        $title->prepend($data->pre2);
        
        $actual = $title->get();
        $expect = '    <title>Pre2 Pre1 This and That Suf1 Suf2</title>' . PHP_EOL;
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetIndent().
     */
    public function testSetIndent()
    {
        $title = new Title;
        $title->setIndent('  ');
        $data = (object) [
            'main' => 'This and That',
        ];
        $title->set($data->main);
        $actual = $title->get();
        $expect = '  <title>This and That</title>' . PHP_EOL;
        $this->assertSame($expect, $actual);
    }
}
